from django.apps import AppConfig


class NotificationsConfig(AppConfig):
    """Configuration class for the Notifications application."""

    # Default field type for autogenerated primary keys
    name = 'notifications'
