from django.apps import AppConfig


class AccountsConfig(AppConfig):
    """Configuration class for the Accounts application."""
    # Default feild type for autogenerated primary keys
    
    name = 'accounts'
